version: '3.8'  
services:
  web:
    image: zqing90/printer-bot:last
    container_name: dingtalk-printer-bot  # 容器名称
    ports:
      - 5000:5000 #应用端口
      - 631:631 # cups服务端口
    restart: always
    volumes:
      - ./config.py:/usr/src/app/app/config.py  # 覆盖配置文件
      - ./cups:/etc/cups # cups配置文件
      - ./uploads:/usr/src/app/app/uploads # 上传文件
      - ./outputs:/usr/src/app/app/outputs # 输出文件
    devices:
      - /dev/bus/usb/003/009:/dev/bus/usb/003/009 # 挂载打印机设备（根据自己的情况而定） 